# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    estest.items.weekdays:
         sun: Sunday
         mon: Monday
         tue: Tuesday
         wed: Wednesday
         thu: Thursday
         fri: Friday
         sat: Saturday
    estest.items.categories:
         cyp: Cypher
         mor: Morpheus
         neo: Neo
         tan: Tank
         tri: Trinity
    estest.items.filters:
         kel: Kelvin
         toa: Toaster
         lof: Lo-Fi

services:
    app.es.create.command:
        class: AppBundle\Command\EsCreateCommand
        arguments:
            - '@es.manager'
            - '%estest.items.weekdays%'
            - '%estest.items.categories%'
            - '%estest.items.filters%'
        tags:
            - { name: console.command }
    app.estest.matcher:
        class: AppBundle\Service\Matcher
        arguments:
            - '@es.manager'
            - '%estest.items.weekdays%'
            - '%estest.items.categories%'
            - '%estest.items.filters%'
